=== apache/incubator-kie-kogito-runtimes/jbpm/jbpm-serverless-workflow/src/main/resources/schema/workflow-01/workflow.json
{
  "$id": "https://wg-serverless.org/workflow.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Workflow is a vendor-neutral specification for defining the format/primitives that the users can use to specify/describe their serverless application flow.",
  "type": "object",
  "javaType": "org.jbpm.serverless.workflow.api.Workflow",
  "javaInterfaces": [
    "java.io.Serializable"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Workflow unique identifier",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "Workflow name",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "description": "Workflow description"
    },
    "version": {
      "type": "string",
      "description": "Workflow version"
    },
    "schemaVersion": {
      "type": "string",
      "description": "Serverless Workflow schema version"
    },
    "owner": {
      "type": "string",
      "description": "Workflow owner"
    },
    "startsAt": {
      "type": "string",
      "description": "Starts at state name"
    },
    "execStatus": {
      "type": "string",
      "enum": [
        "Success",
        "Fail",
        "Timeout",
        "Invalid"
      ],
      "description": "Workflow execution status"
    },
    "metadata": {
      "$ref": "metadata/metadata.json"
    },
    "expressionLanguage": {
      "type": "string",
      "description": "Default expression language to be used throughout the workflow definition"
    },
    "triggers": {
      "type": "array",
      "description": "Trigger Definitions",
      "items": {
        "type": "object",
        "$ref": "events/triggerevent.json"
      }
    },
    "functions": {
      "type": "array",
      "description": "Workflow functions",
      "items": {
        "type": "object",
        "$ref": "functions/function.json"
      }
    },
    "states": {
      "type": "array",
      "description": "State Definitions",
      "items": {
        "type": "object",
        "existingJavaType": "org.jbpm.serverless.workflow.api.interfaces.State",
        "anyOf": [
          {
            "$ref": "states/defaultstate.json"
          },
          {
            "$ref": "states/delaystate.json"
          },
          {
            "$ref": "states/eventstate.json"
          },
          {
            "$ref": "states/operationstate.json"
          },
          {
            "$ref": "states/parallelstate.json"
          },
          {
            "$ref": "states/switchstate.json"
          },
          {
            "$ref": "states/subflowstate.json"
          }
        ]
      }
    },
    "extensions": {
      "type": "array",
      "description": "Workflow Extensions",
      "items": {
        "type": "object",
        "existingJavaType": "org.jbpm.serverless.workflow.api.interfaces.Extension"
      }
    }
  },
  "required": [
    "id",
    "name",
    "version",
    "startsAt",
    "states"
  ]
}

=== apache/incubator-kie-kogito-runtimes/jbpm/jbpm-serverless-workflow/src/test/resources/single-eventstate.sw.json
{
  "id": "function",
  "name": "test-wf",
  "version": "1.0",
  "startsAt": "WaitForGreeting",
  "triggers": [{
    "name": "TestKafkaEvent",
    "source": "testtopic",
    "type": "kafka"
  }],
  "functions": [{
    "name": "greetFunction",
    "type": "script"
  }],
  "states": [{
    "name": "WaitForGreeting",
    "type": "EVENT",
    "end": true,
    "events": [{
      "eventExpression": "TestKafkaEvent",
      "actionMode": "SEQUENTIAL",
      "actions": [{
        "functionref": {
          "refname": "greetFunction",
          "parameters": {
            "script": "System.out.println(\"Hello:\" + ((com.fasterxml.jackson.databind.JsonNode)kcontext.getVariable(\"testtopicVar\")).get(\"firstName\"));"
          }
        }
      }]
    }]
  }]
}
